### ISSUE TITLE
./start.sh: line 1: ./env/bin/python3: No such file or directory

### ISSUE THREAD

**Issue by Cykeek** [cyberstruggle/chalumeau#1]
i followed all the command line by line and found this error at the last:
./start.sh: line 1: ./env/bin/python3: No such file or directory

i already have the latest Python3 and 2 also and other python programs is working fine i don't know is there any problem with this script...

Please help me

![Screenshot from 2020-09-07 10-41-31](https://user-images.githubusercontent.com/70019075/92350446-ba832780-f0f6-11ea-9883-653a9ae12e23.png)

**Comment by safebuffer** [comment]
seems like the python env is not installed , are u sure that ./install.sh worked without any problems ?
1- check if ./env/ exist in the tool directory 
2- if so , just run the following inside the tool dir 
```bash
source env/bin/activate
python3 chalumeau.py
```
